/**
 * Rwanda Administrative Divisions Data
 * Contains all Provinces, Districts, and Sectors for location selection
 */

export const RWANDA_LOCATIONS = {
  "Kigali City": {
    Gasabo: [
      "Bumbogo",
      "Gatsata",
      "Jali",
      "Gikomero",
      "Gisozi",
      "Jabana",
      "Kinyinya",
      "Ndera",
      "Nduba",
      "Remera",
      "Rusororo",
      "Rutunga",
    ],
    Kicukiro: [
      "Gahanga",
      "Gatenga",
      "Gikondo",
      "Kagarama",
      "Kanombe",
      "Kicukiro",
      "Kigarama",
      "Masaka",
      "Niboye",
      "Nyarugunga",
    ],
    Nyarugenge: [
      "Gitega",
      "Kanyinya",
      "Kigali",
      "Kimisagara",
      "Mageragere",
      "Muhima",
      "Nyakabanda",
      "Nyamirambo",
      "Nyarugenge",
      "Rwezamenyo",
    ],
  },
  "Eastern Province": {
    Bugesera: [
      "Gashora",
      "Juru",
      "Kamabuye",
      "Ntarama",
      "Mareba",
      "Mayange",
      "Musenyi",
      "Mwogo",
      "Ngeruka",
      "Nyamata",
      "Nyarugenge",
      "Rilima",
      "Ruhuha",
      "Rweru",
      "Shyara",
    ],
    Gatsibo: [
      "Gasange",
      "Gatsibo",
      "Gitoki",
      "Kageyo",
      "Kiramuruzi",
      "Kiziguro",
      "Muhura",
      "Murambi",
      "Ngarama",
      "Nyagihanga",
      "Remera",
      "Rugarama",
      "Rwimbogo",
    ],
    Kayonza: [
      "Gahini",
      "Kabarondo",
      "Mukarange",
      "Murama",
      "Murundi",
      "Mwiri",
      "Ndego",
      "Nyamirama",
      "Rukara",
      "Ruramira",
      "Rwinkwavu",
    ],
    Kirehe: [
      "Gahara",
      "Gatore",
      "Kigarama",
      "Kigina",
      "Kirehe",
      "Mahama",
      "Mpanga",
      "Musaza",
      "Mushikiri",
      "Nasho",
      "Nyamugari",
      "Nyarubuye",
    ],
    Ngoma: [
      "Jarama",
      "Karembo",
      "Kazo",
      "Kibungo",
      "Mugesera",
      "Murama",
      "Mutenderi",
      "Remera",
      "Rukira",
      "Rukumberi",
      "Rurenge",
      "Sake",
      "Zaza",
    ],
    Nyagatare: [
      "Gatunda",
      "Karama",
      "Karangazi",
      "Katabagemu",
      "Kiyombe",
      "Matimba",
      "Mimuli",
      "Mukama",
      "Musheli",
      "Nyagatare",
      "Rukomo",
      "Rwempasha",
      "Rwimiyaga",
      "Tabagwe",
    ],
    Rwamagana: [
      "Fumbwe",
      "Gahengeri",
      "Gishari",
      "Karenge",
      "Kigabiro",
      "Muhazi",
      "Munyaga",
      "Munyiginya",
      "Musha",
      "Muyumbu",
      "Mwulire",
      "Nyakaliro",
      "Nzige",
      "Rubona",
    ],
  },
  "Northern Province": {
    Burera: [
      "Bungwe",
      "Butaro",
      "Cyanika",
      "Cyeru",
      "Gahunga",
      "Gatebe",
      "Gitovu",
      "Kagogo",
      "Kinoni",
      "Kinyababa",
      "Kivuye",
      "Nemba",
      "Rugatare",
      "Rugengabari",
      "Ruhunde",
      "Rusarabuye",
      "Rwerere",
    ],
    Gicumbi: [
      "Bukure",
      "Bwisige",
      "Byumba",
      "Cyumba",
      "Giti",
      "Kaniga",
      "Manyagiro",
      "Miyove",
      "Mukarange",
      "Muko",
      "Mutete",
      "Nyamiyaga",
      "Nyankenke",
      "Rubaya",
      "Rukomo",
      "Rushaki",
      "Rutare",
      "Ruvune",
      "Rwamiko",
      "Shangasha",
    ],
    Musanze: [
      "Busogo",
      "Cyuve",
      "Gacaca",
      "Gashaki",
      "Gataraga",
      "Kimonyi",
      "Kinigi",
      "Muhoza",
      "Muko",
      "Musanze",
      "Nkotsi",
      "Nyange",
      "Remera",
      "Rwaza",
      "Shingiro",
    ],
    Rulindo: [
      "Base",
      "Burega",
      "Bushoki",
      "Buyoga",
      "Cyinzuzi",
      "Cyungo",
      "Kinihira",
      "Kisaro",
      "Masoro",
      "Mbogo",
      "Murambi",
      "Ngoma",
      "Ntarabana",
      "Rukozo",
      "Rusiga",
      "Shyorongi",
      "Tumba",
    ],
    Gakenke: [
      "Busengo",
      "Coko",
      "Cyabingo",
      "Gakenke",
      "Gashenyi",
      "Gatebe",
      "Janja",
      "Kamubuga",
      "Karambo",
      "Kivuruga",
      "Mataba",
      "Minazi",
      "Muhondo",
      "Muyongwe",
      "Muzo",
      "Nemba",
      "Ruli",
      "Rusasa",
      "Rushashi",
    ],
  },
  "Southern Province": {
    Gisagara: [
      "Gikonko",
      "Gishubi",
      "Kansi",
      "Kibilizi",
      "Kigembe",
      "Mamba",
      "Muganza",
      "Mugombwa",
      "Mukindo",
      "Musha",
      "Ndora",
      "Nyanza",
      "Save",
    ],
    Huye: [
      "Gishamvu",
      "Karama",
      "Kigoma",
      "Kinazi",
      "Maraba",
      "Mbazi",
      "Mukura",
      "Ngoma",
      "Ruhashya",
      "Rusatira",
      "Rwaniro",
      "Simbi",
      "Tumba",
      "Huye",
    ],
    Kamonyi: [
      "Gacurabwenge",
      "Karama",
      "Kayenzi",
      "Kayumbu",
      "Mugina",
      "Musambira",
      "Ngamba",
      "Nyamiyaga",
      "Nyarubaka",
      "Rukoma",
      "Rugarika",
      "Runda",
    ],
    Muhanga: [
      "Cyeza",
      "Kabacuzi",
      "Kibangu",
      "Kiyumba",
      "Muhanga",
      "Mushishiro",
      "Nyabinoni",
      "Nyamabuye",
      "Nyarusange",
      "Rongi",
      "Rugendabari",
      "Shyogwe",
    ],
    Nyamagabe: [
      "Buruhukiro",
      "Cyanika",
      "Gasaka",
      "Gatare",
      "Kaduha",
      "Kamegeri",
      "Kibirizi",
      "Kibumbwe",
      "Kitabi",
      "Mbazi",
      "Mugano",
      "Musange",
      "Musebeya",
      "Mushubi",
      "Nkomane",
      "Tare",
      "Uwinkingi",
    ],
    Nyanza: [
      "Busasamana",
      "Busoro",
      "Cyabakamyi",
      "Kibirizi",
      "Kigoma",
      "Mukingo",
      "Muyira",
      "Ntyazo",
      "Nyagisozi",
      "Rwabicuma",
    ],
    Nyaruguru: [
      "Busanze",
      "Cyahinda",
      "Kibeho",
      "Kivu",
      "Mata",
      "Munini",
      "Ngera",
      "Ngoma",
      "Nyabimata",
      "Nyagisozi",
      "Ruheru",
      "Rusenge",
      "Ruramba",
      "Kivu",
    ],
    Ruhango: [
      "Bweramana",
      "Byimana",
      "Kabagali",
      "Kinazi",
      "Kinihira",
      "Mbuye",
      "Mwendo",
      "Ntongwe",
      "Ruhango",
    ],
  },
  "Western Province": {
    Karongi: [
      "Bwishyura",
      "Gashari",
      "Gishyita",
      "Gisovu",
      "Mubuga",
      "Murambi",
      "Murundi",
      "Mutuntu",
      "Rubengera",
      "Rugabano",
      "Ruganda",
      "Rwankuba",
      "Twumba",
    ],
    Ngororero: [
      "Bwira",
      "Gatumba",
      "Hindiro",
      "Kabaya",
      "Kageyo",
      "Kavumu",
      "Matyazo",
      "Muhanda",
      "Muhororo",
      "Ndaro",
      "Ngororero",
      "Nyange",
      "Sovu",
    ],
    Nyabihu: [
      "Bigogwe",
      "Jenda",
      "Jomba",
      "Karago",
      "Kintobo",
      "Mukamira",
      "Muringa",
      "Rambura",
      "Rugera",
      "Rurembo",
      "Shyira",
    ],
    Nyamasheke: [
      "Bushekeri",
      "Bushenge",
      "Cyato",
      "Gihombo",
      "Kagano",
      "Kanjongo",
      "Karambi",
      "Karengera",
      "Kirimbi",
      "Macuba",
      "Mahembe",
      "Nyabitekeri",
      "Nkanka",
      "Rangiro",
      "Ruharambuga",
      "Shangi",
    ],
    Rubavu: [
      "Bugeshi",
      "Busasamana",
      "Cyanzarwe",
      "Gisenyi",
      "Kanama",
      "Kanzenze",
      "Mudende",
      "Nyakiliba",
      "Nyamyumba",
      "Nyundo",
      "Rubavu",
      "Rugerero",
    ],
    Rutsiro: [
      "Boneza",
      "Gihango",
      "Kigeyo",
      "Kivumu",
      "Manihira",
      "Mukura",
      "Murunda",
      "Musasa",
      "Mushonyi",
      "Mushubati",
      "Nyabirasi",
      "Ruhango",
      "Rusebeya",
    ],
    Rusizi: [
      "Bugarama",
      "Butare",
      "Bweyeye",
      "Gashonga",
      "Giheke",
      "Gihundwe",
      "Gitambi",
      "Kamembe",
      "Muganza",
      "Mururu",
      "Nkanka",
      "Nkombo",
      "Nkungu",
      "Nyakabuye",
      "Nyakarenzo",
      "Nzahaha",
      "Rwimbogo",
    ],
  },
} as const;

// Type definitions
export type Province = keyof typeof RWANDA_LOCATIONS;
export type District<P extends Province> = P extends any
  ? keyof (typeof RWANDA_LOCATIONS)[P]
  : never;

export type Sector<P extends Province, D extends District<P>> = P extends any
  ? D extends keyof (typeof RWANDA_LOCATIONS)[P]
    ? (typeof RWANDA_LOCATIONS)[P][D] extends readonly (infer S)[]
      ? S
      : never
    : never
  : never;

/**
 * Get all provinces
 */
export const getProvinces = (): Province[] => {
  return Object.keys(RWANDA_LOCATIONS) as Province[];
};

/**
 * Get districts by province
 */
export const getDistricts = (province: string): string[] => {
  if (!province || !(province in RWANDA_LOCATIONS)) {
    return [];
  }
  return Object.keys(RWANDA_LOCATIONS[province as Province]);
};

/**
 * Get sectors by province and district
 */
export const getSectors = (province: string, district: string): string[] => {
  if (!province || !district || !(province in RWANDA_LOCATIONS)) {
    return [];
  }

  const districts = RWANDA_LOCATIONS[province as Province];
  if (!(district in districts)) {
    return [];
  }

  return districts[district as keyof typeof districts] as unknown as string[];
};

/**
 * Format full location string
 */
export const formatLocation = (
  sector?: string,
  district?: string,
  province?: string
): string => {
  const parts = [sector, district, province].filter(Boolean);
  return parts.join(", ") || "--";
};
