services:
  postgres:
    image: postgres:15
    # container_name: my_postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KEC
    ports:
      - 5435:5432 # Exposed to your host machine (external access)
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # app:
  #   build:
  #     context: .  # Ensure the Dockerfile path is correct
  #     dockerfile: Dockerfile
  #   container_name: my_app
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     NODE_ENV: development
  #     REDIS_HOST: redis
  #     DATABASE_URL: postgresql://postgres:postgres@localhost:5435/KEC?schema=public  # Corrected DB URL
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:4000/csrf/token"]
  #     interval: 30s
  #     retries: 3
  #   networks:
  #     - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge
